# Generated by Django 4.1.3 on 2023-01-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appregistros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('subtitulo', models.CharField(max_length=60)),
                ('cuerpo', models.CharField(max_length=500)),
                ('autor', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
