# Generated by Django 4.1.3 on 2023-01-18 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appregistros', '0003_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenblog')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appregistros.blog')),
            ],
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
