# Generated by Django 4.1.3 on 2023-01-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appregistros', '0004_imagenblog_delete_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagen'),
        ),
    ]
