# Generated by Django 4.1.3 on 2023-01-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=90)),
                ('cuerpo', models.CharField(max_length=500)),
                ('autor', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('destinatario', models.CharField(max_length=20)),
            ],
        ),
    ]
